### ISSUE TITLE
Roadmap ?

### ISSUE THREAD

**Issue by skinny** [coreycothrum/meta-mender-const-conf#2]
Hi! 

I'm a happy user of this very handy layer and currently prepping to move our project to a more recent Yocto release (aiming for nanbield). Do you have any plans of updating this layer to newer releases ?

Same question stands for https://github.com/coreycothrum/meta-bitbake-variable-substitution but I think opening one issue is enough ;-)

**Comment by coreycothrum** [comment]
Glad it's been of use!

I plan to keep this compatible with YOCTO LTS releases (next is [Scarthgap, due April 2024](https://wiki.yoctoproject.org/wiki/Releases)).

This is intended to mirror the [mender project release schedule](https://github.com/mendersoftware/mender-docs/blob/hosted/302.Release-information/01.Release-schedule/docs.md#current-lts-releases).

**Comment by coreycothrum** [comment]
Glancing at the YOCTO migration notes, I'm not seeing anything that looks like incompatibilities. Have you tried building/use this w/ nanbield? Is it as simple as updating `LAYERSERIES_COMPAT_mender-const-conf` in `layer.conf`?

**Comment by skinny** [comment]
Thanks, will give it a try later this week.

**Comment by skinny** [comment]
I added `nanbield` to `LAYERSERIES_COMPAT_mender-const-conf` and gave it a shot on a previously building nanbield env. Here's the error I got and it's a little cryptic to me at the moment.

```
2023-12-01 10:49:32 - INFO     - /opt/yocto/watchtower/build$ /opt/yocto/watchtower/poky/bitbake/bin/bitbake -c build watchtower-debug
Loading cache: 100% |                                                                                                                                                                                      | ETA:  --:--:--
Loaded 0 entries from dependency cache.
WARNING: /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/base-files/systemd-hostnamed-watcher_20200605.bb: Exception during build_dependencies for do_install                            | ETA:  0:00:58
WARNING: /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/base-files/systemd-hostnamed-watcher_20200605.bb: Error during finalise of /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/base-files/systemd-hostnamed-watcher_20200605.bb
ERROR: ExpansionError during parsing /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/base-files/systemd-hostnamed-watcher_20200605.bb
Traceback (most recent call last):
  File "Var <do_install>", line 1, in <module>
  File "/opt/yocto/watchtower/build/../meta-bitbake-variable-substitution/classes/bitbake-variable-substitution-helpers.bbclass", line 5, in bitbake_variables_search_and_sub_all_FILES_PN(d=<bb.data_smart.DataSmart object at 0x7f3830cc1910>):
       pn         = d.getVar("PN")
    >  files      = d.getVar("FILES:" + pn).split()

bb.data_smart.ExpansionError: Failure expanding variable do_install, expression was     base_do_install
  ${@bitbake_variables_search_and_sub_all_FILES_PN(d)}
    install -d                                                   //image/lib/systemd/system
    install -m 0644 //systemd-hostnamed-watcher.service //image/lib/systemd/system
    install -m 0644 //systemd-hostnamed-watcher.path    //image/lib/systemd/system
 which triggered exception AttributeError: 'NoneType' object has no attribute 'split'
The variable dependency chain for the failure is: do_install

ERROR: Parsing halted due to errors, see error messages above
WARNING: /opt/yocto/watchtower/build/../meta-bitbake-variable-substitution/recipes-examples/example/bb-var-sub-example_1.0.0.bb: Exception during build_dependencies for do_install
WARNING: /opt/yocto/watchtower/build/../meta-bitbake-variable-substitution/recipes-examples/example/bb-var-sub-example_1.0.0.bb: Error during finalise of /opt/yocto/watchtower/build/../meta-bitbake-variable-substitution/recipes-examples/example/bb-var-sub-example_1.0.0.bb
WARNING: /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/systemd-conf/systemd-networkd-watcher_20200605.bb: Exception during build_dependencies for do_install
WARNING: /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/systemd-conf/systemd-networkd-watcher_20200605.bb: Error during finalise of /opt/yocto/watchtower/build/../meta-mender-const-conf/recipes-core/systemd-conf/systemd-networkd-watcher_20200605.bb
WARNING: /opt/yocto/watchtower/build/../poky/meta/recipes-core/images/core-image-ptest.bb: Error during finalise of virtual:mcextend:python3-trove-classifiers:/opt/yocto/watchtower/build/../poky/meta/recipes-core/images/core-image-ptest.bb

Summary: There were 7 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
2023-12-01 10:50:48 - ERROR    - Command "/opt/yocto/watchtower/poky/bitbake/bin/bitbake -c build watchtower-debug" failed with error 1
```

**Comment by skinny** [comment]
`pn         = d.getVar("PN")` in `bitbake-variable-substitution-helpers.bbclass` returns `no-pn` which I cannot explain at the moment


The only reference to `no-pn` can be found in `meta/conf/bitbake.conf` and googling led me to 

https://patchwork.yoctoproject.org/project/oe-core/patch/20230914105052.112829-1-m.schoepfer@rethinkrobotics.com/#13334

https://bugzilla.yoctoproject.org/show_bug.cgi?id=15213

Removing the entry from the file seems to result in a compiling image but I'm going to test this further. Not sure on the impact and/or reason yet

**Comment by coreycothrum** [comment]
What's the output of: `bitbake -e systemd-hostnamed-watcher | grep 'PN='`

on kirkstone, I have:
```
BPN="systemd-hostnamed-watcher"
LOCALEBASEPN="systemd-hostnamed-watcher"
PACKAGE_BEFORE_PN=""
PN="systemd-hostnamed-watcher"
```
---
Can you build just that recipe? (i.e. `bitbake-c build systemd-hostnamed-watcher`)

**Comment by coreycothrum** [comment]
OK, just saw your edits to the previous comment. Good fine.

This may be a (not very well documented) change introduced in [mickledore](https://docs.yoctoproject.org/4.3/migration-guides/release-notes-4.2.html)

What you found in `bitbake.conf` is  add PN to [BB_HASH_CODEPARSER_VALS](https://docs.yoctoproject.org/bitbake/2.6/bitbake-user-manual/bitbake-user-manual-ref-variables.html#term-BB_HASH_CODEPARSER_VALS). Seems like this is an override when parsing recipes to try and reduce bitbake's cache.

---
We need to `BB_HASH_CODEPARSER_VALS:remove` `PN`. Probably best to put in one of the bbclasses of `meta-bitbake-variable-substitution`

**Comment by skinny** [comment]
Tracking changes here : https://github.com/skinny/meta-bitbake-variable-substitution/tree/nanbield

**Comment by coreycothrum** [comment]
maybe a simpler fix; please give this a try:
```
diff --git a/classes/bitbake-variable-substitution-helpers.bbclass b/classes/bitbake-variable-substitution-helpers.bbclass
index ae39ef6..d0d7832 100644
--- a/classes/bitbake-variable-substitution-helpers.bbclass
+++ b/classes/bitbake-variable-substitution-helpers.bbclass
@@ -2,25 +2,27 @@ def bitbake_variables_search_and_sub_all_FILES_PN(d):
   delim      = d.getVar("BITBAKE_VAR_SUB_DELIM")
   deploy_dir = d.getVar("D")
   pn         = d.getVar("PN")
-  files      = d.getVar("FILES:" + pn).split()
+  files      = d.getVar("FILES:" + pn)

   if not deploy_dir:
     bb.warn("no deploy_dir, skipping")
     return "true"

-  for file in files:
-    bitbake_variables_search_and_sub(os.path.join(deploy_dir, file), delim, d)
+  if files:
+    for file in files.split():
+      bitbake_variables_search_and_sub(os.path.join(deploy_dir, file), delim, d)

   return "true"

 def bitbake_variables_search_and_sub_all_SRC_URI(d):
   delim    = d.getVar("BITBAKE_VAR_SUB_DELIM")
   work_dir = d.getVar("WORKDIR")
-  files    = d.getVar("SRC_URI").split()
+  files    = d.getVar("SRC_URI")

-  for file in files:
-    fname = file.split('://')[-1]
-    bitbake_variables_search_and_sub(os.path.join(work_dir, fname), delim, d)
+  if files:
+    for file in files.split():
+      fname = file.split('://')[-1]
+      bitbake_variables_search_and_sub(os.path.join(work_dir, fname), delim, d)

   return "true"
```

**Comment by skinny** [comment]
Hi,

After further testing (currently on mickledore) it looks like the process of variable substitution is broken on every version above langdale. Some (not all) files that are processed by the `bitbake_variables_search_and_sub` function don't work anymore because the "base path" ${D} is not filled correctly. 

For example the openssh package : On langdale it contains the full path to the `image` folder in the openssh folder but on more recent versions that path only contains '/image' 

I added some logging and here's langdale vs mickledore/nanbield : 
```

WARNING: processing path : /opt/yocto/watchtower/build/tmp/work/core2-64-poky-linux/openssh/9.0p1-r0/image/usr/sbin/sshddelkeys.sh True
WARNING: processing file : /opt/yocto/watchtower/build/tmp/work/core2-64-poky-linux/openssh/9.0p1-r0/image/usr/sbin/sshddelkeys.sh
WARNING: processing path : /opt/yocto/watchtower/build/tmp/work/core2-64-poky-linux/openssh/9.0p1-r0/image/usr/lib/systemd/system/sshdgenkeys.service.d/ False
WARNING: processing file : /opt/yocto/watchtower/build/tmp/work/core2-64-poky-linux/openssh/9.0p1-r0/image/usr/lib/systemd/system/sshdgenkeys.service.d/sshdgenkeys.service.conf
```

```
WARNING: processing path : //image/usr/sbin/sshddelkeys.sh False
WARNING: processing path : //image/usr/lib/systemd/system/sshdgenkeys.service.d/ False
```

The boolean at the end is the outcome of the `os.path.isfile` check.

So while the build succeeded with the fixes we discussed earlier, the actual contents of the various files is not replaced and breaks the functionality.

Any suggestions on how to fix or troubleshoot this ?

**Comment by coreycothrum** [comment]
I've got a mickledore build environment and have duplicated what you have last observed.... builds OK but does not replace the variables.

I'm closing this ticket. Will be tracking this here: https://github.com/coreycothrum/meta-bitbake-variable-substitution/issues/2
